INSERT INTO customers(
customer_first_name,
customer_last_name,
customer_address,
customer_address_2,
customer_city,
customer_country,
customer_phone,
customer_email,
customer_credit_card,
customer_credit_card_type,
customer_cc_exp_mo,
customer_cc_exp_year,
customer_bill_address,
customer_bill_city,
customer_bill_post_code,
customer_bill_country,
customer_ship_address,
customer_ship_city,
customer_ship_post_code,
customer_ship_country,
customer_password)
VALUES (
'Hyacinthe',
'Lambersen',
'223 Hovde Street',
'9 Dixon Trail',
'Iwye',
'BY',
'142-191-3470',
'hlambersen0@usda.gov',
'3.54044E+15',
'jcb',
'12',
'2028',
'47279 Fairfield Way',
'Indaial',
'89130-000',
'Belarus',
'LgaD3bRTjrS8',
'631 Buhler Terrace',
'Inozemtsevo',
'357433',
'Brazil'
)
;
